all: picklr

picklr: picklr.cc phpzope.cc pickle.cc tuple.cc dict.cc stackitem.cc tuple.cc utils.cc
	g++ -o picklr -std=c++11 picklr.cc phpzope.cc pickle.cc tuple.cc dict.cc stackitem.cc tuple.cc utils.cc
